name: build
on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      dummy:
        description: 'Just as an example'
        required: false

jobs:
  fetch-toolchain:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container:
      image: espressif/idf:latest
    steps:
      - uses: actions/checkout@v2
      - run: apt update
      - run: apt install -y git wget flex bison gperf python3-pip python-setuptools cmake ninja-build ccache libffi-dev libssl-dev dfu-util
      - run: git clone --recursive https://github.com/espressif/esp-idf.git $HOME/esp-idf
      - run: cd $HOME/esp-idf && ./install.sh
      # - run: source $HOME/esp-idf/export.sh && cd $GITHUB_WORKSPACE && idf.py build
      - run: source $HOME/esp-idf/export.sh && cd $GITHUB_WORKSPACE && mkdir build && cd build && cmake .. -G Ninja && ninja
      # - run: cd $GITHUB_WORKSPACE && idf.py build
